### PR TITLE
Update utility scripts

### PR DESCRIPTION
**Pull request by lorentey**
- Move generate-sources under `Utilities/`
- Upgrade GYB to Python 3
- Adjust `run-full-tests.sh` to build all configurations before running any tests
- Scale down tests to 1/20 the workload by default, unless SWIFT_ATOMICS_LONG_TESTS is set
- Also run tests with TSan enabled

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [X] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]
LGTM.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
