### PR TITLE
Tests: add XCTest manifest for non-SPM based builds

### PR DESCRIPTION
**Pull request by compnerd**
This allows for testing without SPM on non-Darwin targets.  We
explicitly exclude the manifest in SPM based builds because we would
like to use the automatic test discovery functionality from SPM.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @lorentey

**Review by lorentey — APPROVED** [review]
Huh, I forgot we'd need to register the tests. 

In the past some of these array literals triggered "expression is too complex" errors, which is why I removed them -- but IIRC, I also split up the tests into more test cases, so they hopefully won't come back. 🤞

**Pull request merged**
