### PR TITLE
Implement double-wide loads with compare-exchange on arm64 in debug builds with the Swift 5.5 compiler

### PR DESCRIPTION
**Pull request by lorentey**
Resolves https://github.com/apple/swift-atomics/issues/41.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [X] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by stephentyrone — APPROVED** [review]

**Review by stephentyrone — APPROVED** [review]

**Review by glessard — APPROVED** [review]

**Review by glessard — APPROVED** [review]

**Comment by lorentey** [comment]
(Sorry about all the force pushes, I'm wasn't set up to directly test this on M1...)

**Comment by stephentyrone** [comment]
still LGTM.

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
