### PR TITLE
Bump minimum required toolchain to Swift 5.6

### PR DESCRIPTION
**Pull request by lorentey**
### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test

**Comment by stevapple** [comment]
I believe this would break many downstream libraries including NIO (which still supports Swift 5.5). At least we shouldn’t make it though a minor update.

Is there anything we cannot work around?

**Comment by lorentey** [comment]
This shouldn't affect downstream libraries -- SwiftPM is smart enough to limit updates to the most recent tag that supports the toolchain used: so NIO users on 5.5 will continue to get a 1.0 tag, while 5.6+ users will see 1.1 too.

My thinking in selecting 5.6 as the cutoff point is to emulate NIO's rule of supporting three public Swift releases -- with 5.8 nearing shipment, we'll have 5.6, 5.7 and 5.8 by the time this will get tagged. 🤞

**Comment by lorentey** [comment]
(The package not remaining on obsolete language versions forever was a crucial consideration when we initially published the package, and it is explicitly called out in the README. If SPM didn't allow for doing this in minor releases, then we wouldn't have published this as a package in the first place. 😄)

**Pull request merged**
