### PR TITLE
Mark managed atomic constructs Sendable if their payloads are

### LINKED ISSUE #45: The constructs provided by this package need to be marked `Sendable`
Swift 5.5 [introduces `Sendable`][se-0302], which puts new constraints on transferring values across concurrency domains.

[se-0302]: https://github.com/apple/swift-evolution/blob/main/proposals/0302-concurrent-value-and-concurrent-closures.md

The constructs provided by this package are designed to be safe to use without synchronization, so they should be marked `Sendable`. (Hopefully people aren't passing around naked `ManagedAtomic` values, but in case they do, the compiler should know that this is safe.)

### Information

- **Package version:** 1.0.1
- **Platform version:** iOS 15 & macOS Monterey
- **Swift version:** 5.5

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] I've searched for [existing reports](https://github.com/apple/swift-atomics/issues) of the same issue.

### PR DESCRIPTION
**Pull request by lorentey**
Resolves #45.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [X] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
```
17:36:08 
/Users/buildnode/jenkins/workspace/pr-swift-atomics-macos/branch-main/swift-atomics/Sources/Atomics/autogenerated/HighLevelTypes.swift:105:26: error: unknown attribute 'unchecked'
17:36:08 extension ManagedAtomic: @unchecked Sendable where Value: Sendable {}
17:36:08                          ^
17:36:08 /Users/buildnode/jenkins/workspace/pr-swift-atomics-macos/branch-main/swift-atomics/Sources/Atomics/autogenerated/HighLevelTypes.swift:82:14: error: non-final class 'ManagedAtomic' cannot conform to `Sendable`; use `UnsafeSendable`
17:36:08 public class ManagedAtomic<Value: AtomicValue> {
17:36:08              ^
```

ಠ_ಠ

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by jpsim** [comment]
It'd be great to land this so consumers don't need to `@preconcurrency import Atomics`.

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
