### PR TITLE
Resolve some test issues

### PR DESCRIPTION
**Pull request by lorentey**
1. Disable test registration outside of CMake builds.

   This will allow this code base to be built with build systems other than CMake and SPM without these test manifests suddenly appearing again.

2. Split Basics.swift.gyb into 26 different files, one for each test case.

    The original autogenerated swift file is so humongous that it causes problems for some folks.

3. Fix CMake configuration for package tests.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [X] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Wow. This reduced CI build times on Linux from 11min 25s to 1 min 2s. 🤯

**Comment by lorentey** [comment]
Compiling this one file probably needed too much memory for the CI machines, and so they started thrashing, leading to 10x slower build times than expected. 

This also explains the off hand comments I sometimes saw about not being able to build tests at all on constrained machines -- sadly I can't recall any actual bug reports about that, so it remained undiagnosed.

**Comment by kelvin13** [comment]
> Wow. Splitting up that huge test file reduced CI build times from around 10 minutes to roughly 1 minute, on both macOS and Linux. exploding_head 

this whole time i thought the problem was vague type inference… i did not know source file length could have such an impact on typechecker performance…

**Comment by lorentey** [comment]
I suspect it's all about the sheer amount of memory that the compiler needed to hold the hole thing all at once. This also explains why I never really saw this in my local builds -- I don't typically try building things in memory-constrained systems.

**Pull request merged**
