### PR TITLE
_AtomicShims: simplify double word setup

### PR DESCRIPTION
**Pull request by compnerd**
Unify the double word path by using a bit more macro expansion.  The two
differences between 32-bit and 64-bit is:
  - `__uint128_t` vs `uint64_t`
  - 64-bit shifts vs 32-bit shifts

We can simply use a macro to expand out the underlying C type rather
than bifurcating the definitions.  For the second difference, we can
simply use the `__INTPTR_WIDTH__` for the shifts.  We explicitly use
macros for the type-definitions to hide the typedef from Swift.

Use the C11 aggregate constructor to further reduce the code.

### CODE REVIEW

**Comment by compnerd** [comment]
While trying to process the structure here which causes problems for Windows, this duplication was really bothering me.  This reduces the amount of code by about 2/3rds with the same interface set and does so semi-portably (it depends on clang still and doesn't work sufficiently for Windows yet for the same reason as before via the expansion of the prepare/load/store functions.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @lorentey

**Review by lorentey — APPROVED** [review]
Looks good to me! I've no idea why I kept these separate; this looks so much better.

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
